### ISSUE TITLE
破解后无法打开

### ISSUE THREAD

**Issue by lucifer-heaven** [lhajh/Alfred-Powerpack#1]
Mac: 10.14.4
Alfred 3.8.1

从官网上下载的.app 文件能打开。但破译后会崩溃，并且不能通过双击或右键打开。重新覆盖破译后文件可以打开

**Comment by killerlei** [comment]
我的也是同样的情况，打不开，重新安装后才能打开，再破解，重复~

**Comment by lhajh** [comment]
@luc1fev , @killerlei [Alfred 3.8.1(961) 效率神器 - 精品MAC应用分享](https://xclient.info/s/alfred.html?_=7a372c5fb239b94c77ad4868d63f8a67), 可以看看这篇文章下面的这条评论:
```
codesign --sign - --force --deep /Applications/Alfred\ 3.app 
codesign --sign - --force --deep /Applications/Alfred\ 3.app/Contents/Preferences/Alfred\ Preferences.app
```
好像可以解决 3.8.1 无法打开的问题
我目前版本是 3.7, 没有升级
如果还是不行, 可以下载这个页面的 3.7
